### ISSUE TITLE
Error creating repository in Azure DevOps: Value cannot be null. Parameter name: projectName

### ISSUE THREAD

**Issue by francardoso93** [pulumi/pulumi-azuredevops#64] opened 2021-09-08 13:40 UTC
## Steps to reproduce

Try to create a simple Git repository as defined at https://www.pulumi.com/docs/reference/pkg/azuredevops/git/

```
const project = new azureDevops.Project('test-pulumi-project', {
})

const repository = new azureDevops.Git('test-pulumi-repo', {
  projectId: project.id,
  initialization: {
    initType: 'Uninitialized',
  },
})
```

`pulumi up
`

Expected: New repository successfully created
Actual: 
```
error: Error creating repository in Azure DevOps: Value cannot be null.
    Parameter name: projectName
```
This was working fine until last friday, today is the first day I got this. Maybe there was a change (or new bug) at Microsoft API?

**Comment by francardoso93** [comment] 2021-09-13 18:31
I think this was a  bug at Microsoft API. I have just tried again today and it worked fine.

**Comment by stack72** [comment] 2021-09-13 21:17
ah so we can close this out now @francardoso93 ?

**Comment by jkodroff** [comment] 2022-07-25 21:25
Closing as not reproducible since the original supplied Pulumi program is no longer valid (i.e. it fails validation before a preview can be produced). The program now outputs the same issue as #66.

**Closed by jkodroff** 2022-07-25 21:25 UTC
Labels: kind/bug, resolution/no-repro, awaiting-feedback
