### ISSUE TITLE
Create VariableGroup with Azure Key vault

### ISSUE THREAD

**Issue by baoduy** [pulumi/pulumi-azuredevops#62] opened 2021-08-28 12:37 UTC
Hi, I got this issue when creating a VariableGroup with Azure Key vault
```
error: azuredevops:index/variableGroup:VariableGroup resource 'key vault name' has a problem: "variable.0.value": conflicts with key_vault
```
Here is my code
```typescript
const project = await devops.getProject({ name: 'Code' });
  //Create Vairable Group Link to Global Key Vault
  new devops.VariableGroup('MyGroup', {
    projectId: project.id,
    allowAccess: true,
    keyVault: {
      name: 'key vault name',
      serviceEndpointId: 'xxxxx-yyyyy-zzzzz-bbbb-xxxxxxx',
    },
    variables: [{ name: 'key vault variable name' }],
  });
```

**Comment by leezen** [comment] 2021-08-31 16:58
The error implies that somehow the first element of `variables` has set the `value` property (which in your code hasn't happened), so this might a bug in the way the bridge is handling the default value and passing that in (vs. not specifying it at all).

**Comment by jkodroff** [comment] 2022-07-25 18:05
Closing as duplicate of #52

**Closed by jkodroff** 2022-07-25 18:05 UTC
Labels: kind/bug, resolution/duplicate
