### ISSUE TITLE
Looking for an example - create Azure DevOps Release Pipeline

### ISSUE THREAD

**Issue by Aaronontheweb** [pulumi/pulumi-azuredevops#17] opened 2020-09-17 16:07 UTC
Are there any examples of how to use this module to create an Azure DevOps pipeline available? I'm especially interested in having access to a release pipeline.

**Comment by leezen** [comment] 2020-09-24 20:26
Please let us know if https://www.pulumi.com/docs/guides/continuous-delivery/azure-devops/ helps. If not, would be great to get your feedback.

**Comment by Aaronontheweb** [comment] 2020-09-24 20:51
That guide is for how to run Pulumi inside Azure DevOps - what I'm looking for is a guide on using Pulumi to create one using the Pulumi.AzureDevOps package.

**Comment by leezen** [comment] 2020-09-25 17:23
Thanks for the clarification on that. So specifically an example that uses this resource? https://www.pulumi.com/docs/reference/pkg/azuredevops/pipeline/

**Comment by ValkyrieUK** [comment] 2020-10-27 13:16
Would also appreciate a example on how to create pipeline. I'm not even sure if its currently implemented. I believe it would require this API https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/pipelines/create?view=azure-devops-rest-6.0

**Comment by andrewdmoreno** [comment] 2021-03-24 17:33
@leezen I believe what folks are requesting is for a [ReleaseDefinition](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/definitions/get?view=azure-devops-rest-6.0) resource to be made available in the Pulumi AzureDevOps integration. Currently there is only a [BuildDefinition](https://www.pulumi.com/docs/reference/pkg/azuredevops/builddefinition/) resource, which is different. I myself just came looking for docs on that resource and noticed it wasn't there (and ended up at this issue).

**Comment by jkodroff** [comment] 2022-07-25 21:07
Closing as duplicate of #45, but also because this is a missing feature in the upstream provider.

**Closed by jkodroff** 2022-07-25 21:07 UTC
Labels: resolution/duplicate, awaiting-upstream, kind/enhancement
